export const ROUTES = {
  AuthLoading: 'AuthLoading',
  Welcome: 'Welcome',
  Login: 'Login',
  OnboardingWizard: 'OnboardingWizard',
  MainTabs: 'MainTabs',
  AddBooking: 'AddBooking',
  AddClient: 'AddClient',
  Services: 'Services',
  AddService: 'AddService',
  Staff: 'Staff',
  AddStaff: 'AddStaff',
  StaffAvailability: 'StaffAvailability',
  BusinessHours: 'BusinessHours',
  WeeklyCalendar: 'WeeklyCalendar',
  DailySchedule: 'DailySchedule',
  PaymentSettings: 'PaymentSettings',
  NotificationSettings: 'NotificationSettings',
  PublicBooking: 'PublicBooking',
  AppointmentPortal: 'AppointmentPortal',
  Home: 'Home',
  Bookings: 'Bookings',
  Clients: 'Clients',
  Settings: 'Settings',
};
